name: Python application test with Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

   # - name: configure
   #   run: ./configure

    - name: Install dependencies
      run: make install

    - name: Lint with pylink
      run: make lint

    - name: Test with pytest
      run: make test

    - name: Format with Python black
      run: make format
